name: "CI/CD Pipeline for LMS Front-End"
on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - run: npm install -g sass
      - run: sass scss:css
      - run: mkdir dist

      - run: cp -r css dist/
      - run: cp -r pages dist/
      - run: cp -r js dist/
      - run: cp -r index.html dist/
      - run: zip -r dist.zip dist/
      - run: ls -la




      # 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
