name: "CI/CD Pipeline for LMS Front-End"
on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Settingout the latest version
        uses: actions/checkout@v3

      - name: Installing NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing SASS
        run: npm install -g sass

      - name: 'Compilling *.scss files to *.css'
        run: sass scss:css

      - name: Creating the dist directory
        run: mkdir dist

      - name: Copying everything to the dist directory
        run: cp -r css dist/
      - run: cp -r pages dist/
      - run: cp -r js dist/
      - run: cp -r index.html dist/

      - name: Creating a zip file to deployment
        run: zip -r dist.zip dist/
      - run: ls -la

      - name: Authenticating to GCP
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        
      - name: Setting up the gcloud
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy the dist.zip
        run: gcloud compute scp --zone="asia-south1-a" dist.zip dep-9-vm:/opt




      # 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
